### ISSUE TITLE
Remove checkout when you change the delivery method on the checkout page

### ISSUE THREAD

**Issue by RichardPerdaan** [myparcelnl/woocommerce#188]
When you have selected a different shipping method, the checkout should go away as soon it is linked to only 1 shipping method (package).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11389731/49727736-4988b480-fc71-11e8-9d17-583f939c7559.gif)

**Comment by TimBlom** [comment]
Case 00524400: In the latest version the checkout isn't visible after selecting another shipping method (which isn't connected to 'parcel'). However, the chosen delivery method is still selected (e.g. Pick up at PostNL)

**Comment by marcel-k** [comment]
+1 delivery options stay visible when 'afhalen' is selected in version 3.1.4

**Comment by adem-demir** [comment]
case:00448095

**Comment by TimBlom** [comment]
Case 00566661

**Comment by TimBlom** [comment]
Also case 00570090

**Comment by ricklambrechts** [comment]
Hi,

Never supported any project with my code but maybe i can help.
So i don't know how it works with pull requests in this project from outsiders.

I created that it is possible to show the myparcel delivery options only for specific shipping method of specific zone.

[My commit with the changes](https://github.com/ricklambrechts/woocommerce/commit/00f9c93ecaefdd9bfe5abcd82397cd1dee0e2cba)

Ather these changes you will see this:
![image](https://user-images.githubusercontent.com/1367665/59163250-c0a6e480-8afe-11e9-90df-17cd1852ea74.png)

And the myparcel block will only be visible at the selected methods.

**Comment by adem-demir** [comment]
> Hi,
> 
> Never supported any project with my code but maybe i can help.
> So i don't know how it works with pull requests in this project for outsiders.
> 
> I created that it is possible to show the myparcel delivery options only for specific shipping method of specific zone.
> 
> [My commit with the changes](https://github.com/ricklambrechts/woocommerce/commit/00f9c93ecaefdd9bfe5abcd82397cd1dee0e2cba)
> 
> Ather these changes you will see this:
> ![image](https://user-images.githubusercontent.com/1367665/59163250-c0a6e480-8afe-11e9-90df-17cd1852ea74.png)
> 
> And the myparcel block will only be visible at the selected methods.
> ![MyParcel](https://user-images.githubusercontent.com/1367665/59163519-9a834380-8b02-11e9-92d9-ba6f883aa997.gif)
> 
> The shipping zones:
> ![image](https://user-images.githubusercontent.com/1367665/59163296-488cee80-8aff-11e9-955b-bb035cf9d26e.png)

Many thanks for your effort. We have already fixed this issue with our next update. We've only the issue now if you select pick up at store the first hand and you switch to delivery. You don't get the delivery options. See below:

https://monosnap.com/file/VSmI7aGNPjQXO6zXsroej5eeyfREA6

**Comment by ricklambrechts** [comment]
Hi,

This works at mine.

Further i still have the "Bezorgdatum" in the customer emails haha.

**Comment by adem-demir** [comment]
He Rick,

So it works for you with same code as you send before? I tried on our side but as you can see in the video doesn't work correctly.

**Comment by adem-demir** [comment]
released with 3.1.6.
